site_name: CSCS Knowledge Base
# TODO: change to match target deployment
#site_url: https://bcumming.github.io
nav:
  - Home: index.md
  - Getting Started: getting-started/index.md
  - Alps Systems and Platforms: alps-systems/index.md
  - 'Building and Installing Software':
    #- 'Building and Installing Software': building-installing/index.md
    - build-install/index.md
    - 'uenv': build-install/uenv.md
theme:
  name: material
  custom_dir: docs/.overrides
  features:
    - content.code.copy
    - navigation.indexes
  palette:
    primary: white
    accent: red
  logo: assets/cscs-logo.png
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
# TODO: uncomment this to provide a link to the docs in top RHS corner
#repo_url: https://github.com/bcumming/kb-poc
