site_name: CSCS Knowledge Base
# TODO: change to match target deployment
#site_url: https://bcumming.github.io/

# provide a link to the docs in top RHS corner
repo_url: https://github.com/bcumming/kb-poc
# provide a link to "edit this page" to each page
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting started: getting-started/index.md
  - Alps systems and platforms:
    - alps-systems/index.md
    - 'Hardware': alps-systems/hardware.md
    - 'todi': alps-systems/todi.md
  - 'Building and installing software':
    - build-install/index.md
    - 'uenv': build-install/uenv.md
    - 'Cray Programming Environment (CPE)': build-install/cpe.md
    - 'Python with pip': build-install/pip.md
  - 'Frequently asked questions':
    - faq/index.md
    - Developers:
      - faq/developers/index.md
  - 'Rationale':
    - rationale/index.md
theme:
  name: material
  language: en
  #custom_dir: docs/.overrides
  features:
    - content.code.copy
    # add an "edit this page" icon on each page
    - content.action.edit
    - navigation.indexes
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
  icon:
    # set the icon for "edit this page"
    edit: material/pencil
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: assets/cscs-logo.png
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      pipeline:
        - trimmer

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

