#!/usr/bin/env bash

set -e

prefix="$(pwd)"
env="$prefix/pyenv"

[[ ! -d "$env" ]] && echo "=== the environment needs to be configured - run './setup' first" && exit 1

source "$env/bin/activate"

mkdocs serve
