name: publish docs

on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    # TODO: change to main repo when it is moved to eth-cscs organisation
    if: github.repository == 'bcumming/kb-poc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install --upgrade pip
      - run: |
          pip install -r requirements.txt
      - run: rm -rf site
      - run: mkdocs gh-deploy --force
      - run: mkdocs --version
